#docker-compose.yml
version: "3.0"
services:
  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DB_USER: root
      DB_HOST: db
      DB_PASSWORD: root
      ACCESS_TOKEN_EXPIRE_MINUTES: 10
      JWT_SECRET_KEY: your_secret_key
    ports:
      - "8080:8080"
    restart: always
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: testdb
      POSTGRES_PASSWORD: root
